/*
 * FLEX Paging Message Transmitter - ESP32 FSK Transceiver
 * Version and Build Metadata
 *
 * FIRMWARE_VERSION is the single source of truth for the running version.
 * Every module that needs to display or report the version includes this
 * header instead of defining its own copy.
 */

#ifndef VERSION_H
#define VERSION_H

#define FIRMWARE_VERSION "v3.8.75"

#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__

// =============================================================================
// CHANGELOG
// =============================================================================
/*
 * v3.8.0  - v3.6.91 baseline with integrated GSM transport (SIM800L) and WiFi/GSM failover
 * v3.8.1  - MQTT GSM FIX: Reset MQTT client state on transport switch (disconnect client, reset NTP/MQTT flags, 2s grace period), prevents stale WiFi SSL context interfering with GSM TLS handshake
 * v3.8.2  - MQTT GSM SSL SEQUENCE FIX: Moved setTimeout() call to after setMutualAuthParams() (was before gsm_reset_ssl_client()), fixes BR_WRITE_ERROR by preventing timeout reset during SSL client initialization
 * v3.8.3  - MQTT GSM ARCHITECTURAL FIX: Replaced use_gsm_transport local variable (active_network && gsm_connected) with direct active_network==NETWORK_GSM_ACTIVE checks matching v4, eliminates double condition causing wrong code path
 * v3.8.4  - MQTT GSM CRITICAL ORDERING FIX: Moved 5s post-NTP delay and GPRS reconnection check to BEFORE certificate loading (was after), GSM modem needs time to stabilize before SSL initialization begins
 * v3.8.5  - MQTT GSM BUFFER SIZE FIX: Reduced PubSubClient buffer from 2048 to 1024 bytes to prevent BR_WRITE_ERROR SSL handshake timeouts over GSM, empirical testing shows 1024 works reliably while 2048 causes heap fragmentation issues during BearSSL buffer allocation (v4 uses 2048 successfully suggesting different memory management pattern)
 * v3.8.6  - TRANSPORT SWITCH FIX: Removed unnecessary ntp_synced=false reset during transport switch (time doesn't break during 2s switch), added explicit SSL client cleanup (gsm_reset_ssl_client/wifiClientSecure.stop) to prevent SSL errors when switching transports, fixes infinite "MQTT: NTP sync required" loop and SSL connection drops during WiFi↔GSM failover
 * v3.8.7  - GSM TRANSPORT SERVICE CONTROL: Disabled IMAP/ChatGPT services during GSM transport, services automatically suspended when GSM becomes active transport and re-enabled when WiFi restored, boot phase skips service initialization if GSM active
 * v3.8.9  - TRANSPORT SWITCH OPTIMIZATION: Removed 2s transport switch grace period and 5s post-NTP delay before GSM TLS handshake, eliminates unnecessary blocking delays during WiFi/GSM failover, allows immediate MQTT reconnection after transport switch completes
 * v3.8.10 - CODE CLEANUP: Removed unused ESPping library include, removed misleading ChatGPT ping log message (no actual ping performed), renamed last_ping_test to last_ip_check (checks WiFi IP validity every 5min, not ping)
 * v3.8.11 - GSM OPERATOR NAME: Added readable network name to operator log (queries AT+COPS? for alphanumeric name), displays as "Carrier Name (334020)" instead of just numeric code, improves GSM connection visibility
 * v3.8.12 - DISPLAY AUTO-ON: Added reset_oled_timeout() to display_status() so display turns on automatically when status updates occur (state changes, MQTT events, GSM registration), display auto-off after 5min idle, improves visibility of system activity
 * v3.8.13 - NETWORK CONNECTION REDESIGN: Complete architectural rewrite of network connection logic with WiFi scanning before connection attempts, clean separation between boot and runtime reconnection, smart scan intervals (5min with GSM, 1min without), eliminates blind connection attempts and display wake-ups from reconnection spam, replaces convoluted network_execute_connect() with network_boot() + network_reconnect() functions
 * v3.8.14 - GSM A7670SA DRIVER FIX: Changed from SIM800 to SIM7600 TinyGSM driver for proper AT command compatibility, implemented correct POWERKEY pulse-based power management (1s ON pulse, 1.5s OFF pulse), fixes GPRS connection failures and power control issues
 * v3.8.15 - GSM A7670SA POWER MANAGEMENT: Modem stays OFF until needed (power saving), smart initialization checks if modem already on and powers it OFF first, manual AT+CGPADDR=1 IP parsing replaces broken getLocalIP() (fixes display showing raw AT commands), clean IP display format
 * v3.8.16 - GSM A7670SA POWER MANAGEMENT FIX: WiFi boot now explicitly powers OFF modem if detected ON (fixes modem staying on when WiFi available), improved IP parsing to strip CID prefix (fixes "1,10.52.129.153" display issue, now shows clean "10.52.129.153")
 * v3.8.17 - GSM POWER SIMPLIFICATION: Reverted to simple transistor-based power control (HIGH=ON, LOW=OFF) for N2222 hardware modification, removed all POWERKEY pulse logic, removed smart detection/auto-power-off, clean straightforward power management
 * v3.8.18 - GSM IMPROVEMENTS: Fixed IP parsing to remove trailing OK/newlines (clean display), added 1s delay between internet test attempts, implemented network mode fallback (LTE→3G→2G with 3 attempts each for maximum compatibility)
 * v3.8.19 - GSM NETWORK MODE FIX (CRITICAL): Corrected AT+CNMP values (38=LTE, 14=3G, 13=2G - was backwards!), moved network mode setting BEFORE GPRS connection (was after, completely ineffective), proper fallback sequence now works: LTE first → 3G → 2G
 * v3.8.20 - GSM STABILITY: Fixed module name (SIM800L→A7670SA in logs), added 3s stabilization delay after GPRS connection before internet test (fixes first test failure), internet test now succeeds on first attempt
 * v3.8.21 - DISPLAY TIMEOUT FIX: Separated display content updates from timeout resets, removed reset_oled_timeout() from display_status() (architectural fix), display now properly turns off after 5min of no visible state changes, battery checks and periodic updates no longer prevent timeout
 * v3.8.22 - DISPLAY TIMEOUT FIX (FINAL): Removed reset_oled_timeout() from battery monitoring (battery state is environmental not user activity), fixes display staying on due to noisy battery readings crossing power detection threshold every 60s, display now properly times out after 5min of actual user inactivity
 * v3.8.23 - DISPLAY TIMEOUT FIX (SILENT STATES): Added silent states (IDLE, NTP_SYNC, IMAP_PROCESSING) to prevent background operations from waking display, only visible state changes (TX, MQTT, GSM, WiFi operations) wake display, improved state logging to show state names instead of numbers (e.g., "STATE: IDLE -> TRANSMITTING")
 * v3.8.24 - GSM WEB INTERFACE SIMPLIFICATION: Removed Runtime Status and GSM Modem Detection sections from GSM page, removed modem detection endpoint and related functions, Enable GSM toggle now works freely without detection requirement, cleaner user experience
 * v3.8.25 - GSM CONFIG VALIDATION: Use hardware defaults when config contains 0 for GPIO pins (power/RX/TX), baudrate, or connection timeout - applies during both GSM initialization and web page display, ensures consistent fallback behavior across UI and runtime
 * v3.8.26 - MULTIPLE WIFI NETWORK SUPPORT: Device now stores and scans for up to 10 WiFi networks, automatically connects to best available stored network, eliminates blind connection attempts, backup/restore format updated to support multiple networks, web UI manages first network
 * v3.8.27 - NETWORK SETTINGS UX IMPROVEMENT: Replaced input+datalist with traditional dropdown for SSID selection, integrated WiFi scan into dropdown ("Scan for networks..." option), added custom SSID input option, fixes issue where stored networks weren't visible when one was already selected
 * v3.8.28 - IP SETTINGS VISIBILITY OPTIMIZATION: Hide IP/Netmask/Gateway/DNS fields when DHCP is enabled and network is not currently connected, show current DHCP values when connected, show editable fields only for static IP, eliminates confusing default/fake values (0.0.0.0, 192.168.1.100), cleaner form with less visual noise
 * v3.8.29 - PASSWORD VISIBILITY TOGGLE: Added eye icon button to password field for toggling between hidden and plaintext display, improves UX when entering WiFi passwords
 * v3.8.30  - TIMEZONE DROPDOWN: Replaced numeric input with dropdown menu covering UTC-12:00 to UTC+14:00 in 30-minute increments (41 options), supports half-hour timezones like India and Afghanistan
 * v3.8.31  - LIVE CLOCK DISPLAY: Added side-by-side clock cards showing Hardware Clock (UTC) and Local Time with live updates, client-side increment from device timestamp, updates on timezone change
 * v3.8.32  - RF CHIP SHUTDOWN FIX: Added radio.standby() after transmission completes in Core 0 task, fixes RF chip staying in TX mode and transmitting continuous noise after first message, regression from commit ceffdb4 when transmission logic moved to Core 0 without migrating hardware state management
 * v3.8.33  - EXTERNAL RF AMPLIFIER: Complete implementation of configurable external RF amplifier control - configurable GPIO pin (default: TTGO GPIO32, Heltec GPIO22), stabilization delay (20-5000ms, default 200ms), polarity selection toggle (Active-High for NPN driver+P-MOSFET like 2N2222+IRF4905, Active-Low for direct P-MOSFET), enable/disable toggle in FLEX settings page with visual feedback (fields disabled/grayed when off), reserved pin validation (prevents selection of GPIO 0, LoRa pins CS/IRQ/RST/GPIO/SCK/MOSI/MISO, OLED pins SDA/SCL/RST, Battery ADC, LED, VEXT) with real-time UI error display and backend validation, GPIO activated before transmission with configurable delay for bias stabilization, deactivated after transmission complete, fully integrated in settings persistence (save_settings/load_settings/config_to_json/json_to_config) and factory defaults, board-specific pin assignments adapt at compile-time
 * v3.8.34  - WIFI NETWORK UI FIX: Removed STORED:/SCANNED: prefixes causing networks not to connect after save, added blue Add button with validation (SSID, password, static IP fields), new /api/wifi/add endpoint for adding networks without restart, Save Configuration now triggers device restart
 * v3.8.35  - BOOT STATE MACHINE REFACTOR: Renamed BOOT_WIFI_* to BOOT_NETWORK_* for transport-agnostic naming,
 *            added BOOT_AP_COMPLETE state to prevent NTP sync attempts in AP-only mode (no WiFi, no GSM, avoiding RTC corruption),
 *            restored WiFi health check with conditional network_reconnect() calls (fixes webserver slowness regression)
 * v3.8.36  - WIFI CONFIG UX IMPROVEMENTS: Removed page refresh after adding network (dynamic dropdown update), added
 *            onSSIDChange() after WiFi scan completion/error to properly reset form fields
 * v3.8.37  - TIMEZONE DROPDOWN IMPROVEMENT: Replaced 41 generic options with 31 common timezones with descriptive
 *            names (cities/regions), removed rarely-used intermediate offsets, changed label to "Local Timezone"
 * v3.8.38  - BOOT INITIALIZATION FIX: Disabled default watchdog before SPIFFS format, early display initialization
 *            shows "Initializing Device..." message during first boot, eliminates 60s watchdog errors and black screen
 * v3.8.39  - FLEX CAPCODE VALIDATION: Implemented proper FLEX protocol capcode validation with gap detection,
 *            valid ranges: 1-1933312, 1998849-2031614, 2101249-4291000000, updated max from 4294967295 to 4291000000
 * v3.8.40  - TX POWER VALIDATION FIX: Enforce 2 dBm minimum power (was 0), add radio init fallback to prevent halt on invalid power settings,
 *            fixes device halt on reboot when TX power set below hardware minimum
 * v3.8.41  - WIFI TRANSPORT SWITCH FIX: Added missing transport switch logic to check_wifi_connection(), WiFi reconnection now properly powers off GSM modem and updates active network state,
 *            fixes webserver inaccessibility and stale GSM IP display when switching from GSM to WiFi; DISPLAY BOOT FIX: Network status line now shows correct transport during boot (WiFi vs GSM),
 *            uses device_state to determine active connection attempt instead of generic fallback logic; DISPLAY UX: Simplified state messages by removing transport prefixes (WiFi/GSM) from State line,
 *            network line already shows explicit transport type, eliminates redundant information
 * v3.8.42  - NETWORK FALLBACK FIX: WiFi connection failure now attempts GSM before falling back to AP mode (was going directly to AP),
 *            fixes issue where device entered AP mode despite GSM being enabled and available, proper fallback sequence: WiFi → GSM (all network modes) → AP_MODE
 * v3.8.43  - PERIODIC WIFI RECONNECT FIX: Added periodic network_reconnect() timer in loop (60s when GSM active, 30s when no network) to restore WiFi availability scanning,
 *            fixes issue where device stayed on GSM indefinitely without checking for WiFi; added STATE_WIFI_CONNECTING guard to prevent scan interference during WiFi connection
 * v3.8.44  - MQTT DISPLAY COUNTER FIX: Fixed mqtt_connection_attempt counter never incrementing, display now shows retry count "MQTT [1]...", "MQTT [2]..." during reconnection attempts
 * v3.8.45  - MQTT TRANSPORT SWITCH FIX: Added mqttClient.disconnect() before SSL client cleanup during transport switch (WiFi↔GSM), prevents SSL BR_WRITE_ERROR and stale connection state causing reconnection failures
 * v3.8.46  - MQTT TRANSPORT SWITCH FIX (CRITICAL): Force mqttClient.disconnect() without checking connected() state (underlying transport change causes false negative), added 100ms delay after disconnect for socket cleanup, eliminates "Socket dropped unexpectedly" SSL warning
 * v3.8.47  - WIFI SCAN ERROR HANDLING: Added validation and recovery for WiFi scan failures (WIFI_SCAN_FAILED/-2), reinitializes WiFi and retries once on failure, prevents infinite loop of failed scans when GSM is active, clearer error messages
 * v3.8.48  - MQTT TRANSPORT SWITCH ORDER FIX: Call network_update_active_state() BEFORE gsm_disconnect/power_off during GSM→WiFi switch, ensures mqttClient.disconnect() executes while GSM socket still active, eliminates SSL write errors and BR_WRITE_ERROR on transport switch
 * v3.8.49  - WEB WIFI SCAN ERROR HANDLING: Added WiFi scan failure validation and recovery in /api/wifi/scan endpoint, handles WIFI_SCAN_FAILED errors same as wifi_ssid_scan(), fixes network dropdown not updating when scan fails
 * v3.8.50  - WEB WIFI SCAN ASYNC FIX: Changed /api/wifi/scan to use async WiFi.scanNetworks(true) with webServer.handleClient() calls during wait, prevents blocking loop() and allows web interface to remain responsive during scan, fixes dropdown never updating issue
 * v3.8.51  - WEB JAVASCRIPT LOAD ORDER FIX: Moved static_ip_script (containing onSSIDChange function) to be sent before network_section HTML, eliminates "onSSIDChange is not defined" ReferenceError on first page load
 * v3.8.52  - MANUAL NETWORK MODE CONTROL: Added AT+NETWORK command to force specific transport mode (AUTO/WIFI/GSM/AP) until reboot or manual change, disables automatic transport fallback when mode is locked, locked modes retry connection indefinitely with appropriate intervals (WiFi 60s, GSM 300s, AP no retries), display shows asterisk indicator (WiFi*, GSM*, AP*) when mode is locked, enables dedicated transport testing and prevents unwanted switching in field deployments
 * v3.8.53  - MQTT FAILURE HANDLING ARCHITECTURAL FIX: Moved WiFi failure counter logic from mqtt_loop() to mqtt_connect() for architectural consistency, both WiFi (3 attempts→suspend) and GSM (5 attempts→restart) failure handling now centralized in mqtt_connect() where connection attempt occurs, mqtt_loop() simplified to only coordinate reconnection timing with backoff, cleaner separation of responsibilities (connection logic vs scheduling logic), removed unused mqtt_transmit_suppressed variable
 * v3.8.54  - MQTT COUNTER RESET CONSISTENCY: Moved mqtt_failed_cycles reset from mqtt_loop() to mqtt_connect() on successful connection, both GSM (mqtt_gsm_attempt_counter) and WiFi (mqtt_failed_cycles) counters now reset in same location for 100% architectural consistency, mqtt_connect() now fully self-contained for all connection state management
 * v3.8.55  - CRITICAL SERVICE ISOLATION FIX: Removed transmission_guard_active() blocking from webServer.handleClient() and mqtt_loop() only - these critical services now continue processing during TX since transmission runs isolated on Core 0 with thread-safe queue, fixes HTTP/MQTT request dropping during transmission; IMAP and ChatGPT remain protected (non-critical, heavy SSL/HTTP operations can wait)
 * v3.8.56  - MQTT AUTO-RETRY & FAILURE NOTIFICATIONS: Added auto-retry mechanism (configurable retry interval: 5-1440 minutes) replacing indefinite suspension, added failure notifications toggle (sends pager alert on suspension), added Recent Activity card with detailed event logging including datetime/frequency/capcode, dynamic transmission status tracking in activity log, shortened UI labels ("Boot Delay" and "Retry Time"), added MQTTActivity struct with comprehensive event tracking; CHATGPT CONSISTENCY: Renamed notify_on_failure → chatgpt_notify_failures for consistency with MQTT, changed default to failure notifications enabled, updated UI label to "Failure notifications"; UI: Added transmission status icons (✅/❌) for MQTT events with conditional display (only for events that transmit RF), backup/restore JSON support for all new fields
 * v3.8.57  - CHATGPT JSON ESCAPE FIX: Added json_escape_string() for proper JSON encoding, sanitize_chatgpt_prompt() for
 *            input normalization (whitespace/newlines), prevents HTTP 400 errors from malformed JSON with special characters
 * v3.8.58  - PERSISTENT SPIFFS LOG SYSTEM: Implemented /serial.log file (250KB limit, 50KB keep on rotate),
 *            single logMessage() function handles all logging (Serial + file + syslog), deleted old log buffers
 *            (12KB freed), pre-NTP timestamps show uptime (0000-00-00 HH:MM:SS), post-NTP show datetime
 *            (YYYY-MM-DD HH:MM:SS), file.flush() ensures writes committed to flash, AT+LOGS?N (default 25)
 *            and AT+RMLOG commands, status page displays 100 lines with auto-scroll to bottom, chronological
 *            order (oldest→newest), live logs toggle with configurable refresh interval (1-60s, default 5s)
 * v3.8.59  - RTC TIME INTEGRATION: Log timestamps now use system_time_initialized flag instead of ntp_synced,
 *            enables immediate timestamped logging when RTC provides time at boot (eliminates 0000-00-00 timestamps
 *            for RTC-equipped devices), boot sequence skips NTP blocking when RTC time valid (faster boot),
 *            MQTT/ChatGPT use system_time_initialized for time validation (works with RTC or NTP), periodic NTP
 *            still runs to verify/update RTC when network available
 * v3.8.60  - STATUS PAGE UX FIX: Lines count input now refreshes log display immediately when changed,
 *            works even with live logs disabled (calls pollLogs() after updating linesToShow variable)
 * v3.8.61  - SPIFFS LOG SIZE FIX + LOG WRITE BUFFER: Corrected MAX_LOG_FILE_SIZE (256000->32768) and
 *            LOG_TRUNCATE_SIZE (51200->8192) to fit within 128KB SPIFFS partition (min_spiffs scheme);
 *            replaced per-message open/write/flush/close with 2KB RAM buffer; flushes to SPIFFS as single
 *            write when full (>=1536B) or every 1s via loop()
 * v3.8.62  - SPIFFS WRITE HARDENING: Added file.flush() before file.close() in all config write functions
 *            (saveCertificateToSPIFFS, save_imap_config, save_runtime_settings, chatgpt_save_config, restore
 *            handler); restore handler now checks print() return value and logs error on 0-byte write
 * v3.8.63  - MQTT UNIFIED FAILURE COUNTER: Single mqtt_failed_cycles counter for both transports, single decision point in mqtt_loop(), transport-aware threshold (WiFi/GSM: 3 attempts→reboot), persistent reboot loop guard (3 reboots→suspend), removed mqtt_gsm_attempt_counter/mqtt_gsm_max_attempts, mqtt_connect() now only performs diagnostics and transport-specific cleanup (gsm_reset_ssl_client), all counter/reboot/suspend logic centralized in mqtt_loop()
 * v3.8.64  - MQTT RETRY LIMITS EXTENDED + TRANSPORT RESET FIX: Changed limits from 3×3 to 5×5 (25 total attempts before suspension), mqtt_reboot_count now resets on transport switch (GSM↔WiFi) and AT+RESET command, fixes permanent MQTT suspension after transport change due to stale counter from previous transport
 * v3.8.65  - MQTT TRANSPORT CRASH FIX: Added !mqtt_suspended guard to mqttClient.disconnect() in on_network_changed(), prevents LoadProhibited crash when switching transports with MQTT suspended (client never connected), separated disconnect logic from counter reset (counter reset always executes, disconnect only when client valid)
 * v3.8.66  - LOG RETENTION IMPROVED: Doubled log file limits (MAX_LOG_FILE_SIZE 32KB→64KB, LOG_TRUNCATE_SIZE 8KB→32KB), added rotation notification message to Serial output, retains 4x more history before truncation
 * v3.8.67  - MQTT COUNTER RESET FIX + DISPLAY UX: Fixed mqtt_connection_attempt counter resetting on failure instead of success (display stuck at "[1]"), counter now properly increments across retry attempts and resets only when connection succeeds; display shows "Ready (M)" when MQTT connected (otherwise just "Ready"), removed "*" asterisk from all transport indicators (GSM/WiFi/AP) for cleaner display
 * v3.8.68  - AP MODE LED HEARTBEAT: Status LED heartbeat now fires 4x more often while ap_mode_active is true (interval HEARTBEAT_INTERVAL/4, 15s instead of 60s), unchanged otherwise, makes AP mode visually distinguishable at a glance without checking the display
 * v3.8.69  - HARDENING PASS (imported from FlexDevice review): Serial.setTxBufferSize(1024) before Serial.begin() prevents truncation on large AT responses (AT+LOGS?, AT+DEVICE?), extracted rfamp_init/rfamp_enable/rfamp_disable helpers in hardware.cpp replacing 3x duplicated inline RF amplifier GPIO logic, flex_encode_and_store() now logs encoding failures instead of failing silently, EMR pattern bytes moved to named EMR_PATTERN/EMR_PATTERN_SIZE constants in config.h; behavior-preserving refactor, no functional changes
 * v3.8.70  - CAPCODE VALIDATION BYPASS FIX: validate_flex_capcode() took a uint32_t parameter while every caller held a uint64_t capcode, so out-of-range 64-bit values got silently truncated before the range check ran; validate_flex_capcode() was also only called from 3 of ~11 capcode entry points (REST API, MQTT, Grafana webhook, IMAP, AT+MSG had no validation at all). Widened every uint32_t capcode field/parameter to uint64_t across transmission.h/.cpp, imap.h/.cpp, chatgpt.h/.cpp, mqtt.h/.cpp, and the web/API JSON handlers; fixed two strtoul (32-bit) calls that should have been strtoull in web_handlers_api.cpp and grafana.cpp; consolidated capcode range validation into a single chokepoint inside queue_add_message() so every transmission path (web UI, REST API, MQTT, Grafana, IMAP, ChatGPT, AT+MSG, battery/power alerts) is now validated the same way
 * v3.8.71  - CAPCODE UPPER BOUND FIX: validate_flex_capcode() rejected valid long-address capcodes above 4291000000, but the FLEX protocol's actual long-address ceiling (tinyflex.h is_longaddr_valid(), Reference Document A 5.15.5) is 4297068542; raised the upper bound to 4297068542ULL to match tinyflex.h and stop rejecting valid capcodes in the 4291000001-4297068542 range
 * v3.8.72  - SOURCE TREE REORGANIZATION: moved all 40 root-level .cpp/.h files into src/core/, src/protocol/, src/network/, src/services/, src/web/ grouped by function (flex-fsk-tx-v2.ino, include/, host/, scripts/, docs/ unchanged); rewrote every local #include to be directory-relative to the including file itself (e.g. "../core/config.h" from src/network/, "../../include/boards/boards.h" from any src/<group>/ file) since this toolchain does not add src/ itself to the include search path; updated scripts/flex-build-upload.sh's version.h lookup path; behavior-preserving, no functional changes
 * v3.8.73  - Moved version.h out of src/core/ to src/version.h directly, since it's a project-wide constant rather than belonging to any one functional group; updated every #include referencing it (flex-fsk-tx-v2.ino, storage.cpp, at_commands.cpp, web_server.cpp, web_handlers_device.cpp, web_handlers_settings.cpp) and scripts/flex-build-upload.sh's version.h lookup path; behavior-preserving, no functional changes
 * v3.8.74  - Added platformio.ini for optional PlatformIO builds (ttgo/heltec/ttgo-full/heltec-full envs) alongside the existing arduino-cli path, with no source files touched; src_dir points at the repo root with build_src_filter compiling flex-fsk-tx-v2.ino + src/** while excluding host/, bkp/, scripts/, docs/, include/tinyflex/demos/; platform pinned to the pioarduino espressif32 fork since the official PlatformIO Registry platform only bundles arduino-esp32 2.0.17 (ESP-IDF 4.4), lacking the ESP-IDF 5.x watchdog API (esp_task_wdt_config_t) hardware.cpp already relies on; verified all 4 envs compile clean and the arduino-cli build path is unaffected (byte-identical flash/RAM usage to before this change)
 * v3.8.75  - Restructured PlatformIO envs from ttgo/heltec/ttgo-full/heltec-full into five feature tiers per board (-wifi: no optional modules, -wifi-all: RTC+IMAP+ChatGPT, -gsm: GSM only, -gsm-rtc: GSM+RTC, -full: everything), 10 envs total; IMAP/ChatGPT intentionally left out of the -gsm profiles since both are already auto-suspended at runtime while GSM is the active transport (network.cpp); no source files touched, all 10 envs verified compiling clean
 */

#endif // VERSION_H
